/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.san.form;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author sociepka
 */
public class AddProspect extends javax.swing.JDialog {

    /**
     * Creates new form AddClient
     */
    public AddProspect(java.awt.Frame parent, boolean modal) throws IOException {
        super(parent, modal);
        initComponents();
         /**
        * changer l'icone de la fenêtre
        */
            BufferedImage img = ImageIO.read(AddProspect.class.getResource("/com/san/form/logo.png"));
            
            setIconImage(img);
         /**
        * Commande pour centrer la fenêtre dans l'écran
        */
       setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titre = new javax.swing.JLabel();
        lbPrenom = new javax.swing.JLabel();
        lbNom = new javax.swing.JLabel();
        chpPrenom = new javax.swing.JTextField();
        chpNom = new javax.swing.JTextField();
        Liste = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        lbNomsociete = new javax.swing.JLabel();
        chpNomsociete = new javax.swing.JTextField();
        lbAddresse1 = new javax.swing.JLabel();
        lbCodepostal = new javax.swing.JLabel();
        chpAdresse1 = new javax.swing.JTextField();
        chpAdresse2 = new javax.swing.JTextField();
        chpCodepostal = new javax.swing.JTextField();
        lbVille = new javax.swing.JLabel();
        chpVille = new javax.swing.JTextField();
        lbPays = new javax.swing.JLabel();
        chpPays = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        chpEmail = new javax.swing.JTextField();
        lbSiret = new javax.swing.JLabel();
        chpSiret = new javax.swing.JTextField();
        lbTelfixe = new javax.swing.JLabel();
        chpTelfixe = new javax.swing.JTextField();
        lbTelportable = new javax.swing.JLabel();
        chpTelportable = new javax.swing.JTextField();
        lbDatevisite = new javax.swing.JLabel();
        chpDatevisite = new javax.swing.JTextField();
        titreContact = new javax.swing.JLabel();
        fondcouleur1 = new javax.swing.JPanel();
        fondcouleur2 = new javax.swing.JPanel();
        imagefond = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mRetour = new javax.swing.JMenu();
        mAjouter = new javax.swing.JMenu();
        mModifier = new javax.swing.JMenu();
        mAide = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ToutBois - Gestion prospects");

        jPanel1.setBackground(new java.awt.Color(187, 235, 219));
        jPanel1.setLayout(null);

        Titre.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        Titre.setText("Gestion des prospects");
        jPanel1.add(Titre);
        Titre.setBounds(20, 10, 310, 30);

        lbPrenom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPrenom.setText("Prénom");
        jPanel1.add(lbPrenom);
        lbPrenom.setBounds(10, 200, 47, 15);

        lbNom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNom.setText("Nom");
        jPanel1.add(lbNom);
        lbNom.setBounds(210, 200, 27, 20);

        chpPrenom.setColumns(10);
        chpPrenom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chpPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chpPrenomActionPerformed(evt);
            }
        });
        jPanel1.add(chpPrenom);
        chpPrenom.setBounds(90, 200, 106, 21);

        chpNom.setColumns(10);
        chpNom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chpNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chpNomActionPerformed(evt);
            }
        });
        jPanel1.add(chpNom);
        chpNom.setBounds(240, 200, 106, 21);

        jList1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item2", "Item3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Liste.setViewportView(jList1);

        jPanel1.add(Liste);
        Liste.setBounds(10, 270, 580, 138);

        lbNomsociete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNomsociete.setText("Nom de la Société");
        jPanel1.add(lbNomsociete);
        lbNomsociete.setBounds(340, 20, 109, 20);

        chpNomsociete.setColumns(10);
        chpNomsociete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(chpNomsociete);
        chpNomsociete.setBounds(460, 20, 126, 23);

        lbAddresse1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbAddresse1.setText("Adresse 1");
        jPanel1.add(lbAddresse1);
        lbAddresse1.setBounds(10, 90, 60, 20);

        lbCodepostal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCodepostal.setText("Code Postal");
        jPanel1.add(lbCodepostal);
        lbCodepostal.setBounds(10, 120, 73, 15);

        chpAdresse1.setColumns(20);
        chpAdresse1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chpAdresse1.setText("numero, nom de rue");
        chpAdresse1.setToolTipText("");
        jPanel1.add(chpAdresse1);
        chpAdresse1.setBounds(90, 90, 260, 21);

        chpAdresse2.setColumns(20);
        chpAdresse2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chpAdresse2.setText("complément d'adresse");
        jPanel1.add(chpAdresse2);
        chpAdresse2.setBounds(356, 90, 230, 21);

        chpCodepostal.setColumns(10);
        chpCodepostal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(chpCodepostal);
        chpCodepostal.setBounds(90, 120, 106, 21);

        lbVille.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbVille.setText("Ville");
        jPanel1.add(lbVille);
        lbVille.setBounds(210, 120, 24, 20);

        chpVille.setColumns(10);
        chpVille.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(chpVille);
        chpVille.setBounds(240, 120, 110, 21);

        lbPays.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPays.setText("Pays");
        jPanel1.add(lbPays);
        lbPays.setBounds(360, 120, 28, 20);

        chpPays.setColumns(10);
        chpPays.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(chpPays);
        chpPays.setBounds(396, 120, 190, 21);

        lbEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbEmail.setText("Email");
        jPanel1.add(lbEmail);
        lbEmail.setBounds(20, 230, 31, 20);

        chpEmail.setColumns(10);
        chpEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(chpEmail);
        chpEmail.setBounds(90, 230, 106, 21);

        lbSiret.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSiret.setText("SIRET");
        jPanel1.add(lbSiret);
        lbSiret.setBounds(10, 60, 36, 20);

        chpSiret.setColumns(14);
        chpSiret.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(chpSiret);
        chpSiret.setBounds(90, 60, 146, 21);

        lbTelfixe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTelfixe.setText("Téléphone fixe");
        jPanel1.add(lbTelfixe);
        lbTelfixe.setBounds(360, 200, 89, 20);

        chpTelfixe.setColumns(10);
        chpTelfixe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(chpTelfixe);
        chpTelfixe.setBounds(480, 200, 106, 21);

        lbTelportable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTelportable.setText("Téléphone portable");
        jPanel1.add(lbTelportable);
        lbTelportable.setBounds(360, 230, 119, 20);

        chpTelportable.setColumns(10);
        chpTelportable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(chpTelportable);
        chpTelportable.setBounds(480, 230, 106, 21);

        lbDatevisite.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDatevisite.setText("Date de la dernière visite");
        jPanel1.add(lbDatevisite);
        lbDatevisite.setBounds(280, 60, 152, 20);

        chpDatevisite.setColumns(10);
        chpDatevisite.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chpDatevisite.setText("jj/mm/aaaa");
        jPanel1.add(chpDatevisite);
        chpDatevisite.setBounds(480, 60, 106, 21);

        titreContact.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titreContact.setText("Contact de la société");
        jPanel1.add(titreContact);
        titreContact.setBounds(20, 160, 187, 22);

        fondcouleur1.setBackground(new java.awt.Color(191, 191, 179));

        javax.swing.GroupLayout fondcouleur1Layout = new javax.swing.GroupLayout(fondcouleur1);
        fondcouleur1.setLayout(fondcouleur1Layout);
        fondcouleur1Layout.setHorizontalGroup(
            fondcouleur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        fondcouleur1Layout.setVerticalGroup(
            fondcouleur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(fondcouleur1);
        fondcouleur1.setBounds(0, 50, 600, 100);

        fondcouleur2.setBackground(new java.awt.Color(191, 191, 179));

        javax.swing.GroupLayout fondcouleur2Layout = new javax.swing.GroupLayout(fondcouleur2);
        fondcouleur2.setLayout(fondcouleur2Layout);
        fondcouleur2Layout.setHorizontalGroup(
            fondcouleur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        fondcouleur2Layout.setVerticalGroup(
            fondcouleur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(fondcouleur2);
        fondcouleur2.setBounds(0, 190, 600, 70);

        imagefond.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        imagefond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/san/form/meubles1.jpg"))); // NOI18N
        jPanel1.add(imagefond);
        imagefond.setBounds(0, -30, 600, 480);

        mRetour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/san/form/iconearbre.jpg"))); // NOI18N
        mRetour.setText("Retour à la fenêtre principale");
        mRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mRetourMouseClicked(evt);
            }
        });
        jMenuBar1.add(mRetour);

        mAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/san/form/iconeplus.jpg"))); // NOI18N
        mAjouter.setText("Ajouter un nouveau client");
        jMenuBar1.add(mAjouter);

        mModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/san/form/iconemodif.jpg"))); // NOI18N
        mModifier.setText("Modifier un client");
        jMenuBar1.add(mModifier);

        mAide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/san/form/iconeaide.jpg"))); // NOI18N
        mAide.setText("Aide");
        jMenuBar1.add(mAide);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chpPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chpPrenomActionPerformed

    }//GEN-LAST:event_chpPrenomActionPerformed

    private void chpNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chpNomActionPerformed

    }//GEN-LAST:event_chpNomActionPerformed

    private void mRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mRetourMouseClicked
        dispose();
    }//GEN-LAST:event_mRetourMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProspect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProspect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProspect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProspect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddProspect dialog = null;
                try {
                    dialog = new AddProspect(new javax.swing.JFrame(), true);
                } catch (IOException ex) {
                    Logger.getLogger(AddProspect.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Liste;
    private javax.swing.JLabel Titre;
    private javax.swing.JTextField chpAdresse1;
    private javax.swing.JTextField chpAdresse2;
    private javax.swing.JTextField chpCodepostal;
    private javax.swing.JTextField chpDatevisite;
    private javax.swing.JTextField chpEmail;
    private javax.swing.JTextField chpNom;
    private javax.swing.JTextField chpNomsociete;
    private javax.swing.JTextField chpPays;
    private javax.swing.JTextField chpPrenom;
    private javax.swing.JTextField chpSiret;
    private javax.swing.JTextField chpTelfixe;
    private javax.swing.JTextField chpTelportable;
    private javax.swing.JTextField chpVille;
    private javax.swing.JPanel fondcouleur1;
    private javax.swing.JPanel fondcouleur2;
    private javax.swing.JLabel imagefond;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAddresse1;
    private javax.swing.JLabel lbCodepostal;
    private javax.swing.JLabel lbDatevisite;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbNom;
    private javax.swing.JLabel lbNomsociete;
    private javax.swing.JLabel lbPays;
    private javax.swing.JLabel lbPrenom;
    private javax.swing.JLabel lbSiret;
    private javax.swing.JLabel lbTelfixe;
    private javax.swing.JLabel lbTelportable;
    private javax.swing.JLabel lbVille;
    private javax.swing.JMenu mAide;
    private javax.swing.JMenu mAjouter;
    private javax.swing.JMenu mModifier;
    private javax.swing.JMenu mRetour;
    private javax.swing.JLabel titreContact;
    // End of variables declaration//GEN-END:variables
}
