/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulaires;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;


/**
 *
 * @author sociepka
 */
public class FenetrePrincipaleFrame extends javax.swing.JFrame {

    /**
     * Creates new form FenetrePrincipaleFrame
     * Constructeur avec des arguments ajoutés pour créer la fenêtre à partir de la classe "Principale"
     * @throws java.io.IOException
     */
    public FenetrePrincipaleFrame(java.awt.Frame parent, boolean modal) throws IOException {
       //super(parent, modal);
        /**
        * changer l'icone de la fenêtre
        */
       
       //BufferedImage img = ImageIO.read(FenetrePrincipaleFrame.class.getResource("Formulaires/logo.png"));
       //setIconImage(img);
            
       initComponents();
       initialise () ;
       
       /**
        * Commande pour centrer la fenêtre dans l'écran
        */
       setLocationRelativeTo(null);
    }
    
    private void initialise(){
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
    /**
     * Constructeur d'origine sans arguments
     */
public FenetrePrincipaleFrame() {
    

       
       initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        lbPresentation = new javax.swing.JLabel();
        imageArbres = new javax.swing.JButton();
        lbToutBoiscest = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbBienvenue = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFichier = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mRepresentants = new javax.swing.JMenu();
        mClients = new javax.swing.JMenu();
        mProspects = new javax.swing.JMenu();
        mAide = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Logiciel de gestion ToutBois");
        setBackground(new java.awt.Color(187, 235, 219));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        lbPresentation.setBackground(new java.awt.Color(255, 255, 255));
        lbPresentation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbPresentation.setText("Logiciel de gestion des représentants et de leurs clients présents et potentiels !");
        jPanel1.add(lbPresentation);
        lbPresentation.setBounds(10, 60, 550, 50);

        imageArbres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formulaires/téléchargement.jpg"))); // NOI18N
        imageArbres.setBorder(null);
        imageArbres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageArbresActionPerformed(evt);
            }
        });
        jPanel1.add(imageArbres);
        imageArbres.setBounds(290, 140, 275, 183);

        lbToutBoiscest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbToutBoiscest.setText("ToutBois, c'est :");
        jPanel1.add(lbToutBoiscest);
        lbToutBoiscest.setBounds(30, 120, 210, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("x représentants");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 200, 160, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("x clients");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 230, 110, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("x prospects");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 260, 130, 22);

        lbBienvenue.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        lbBienvenue.setText("Bienvenue chez ToutBois !!");
        jPanel1.add(lbBienvenue);
        lbBienvenue.setBounds(20, 20, 560, 37);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formulaires/meubles1.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 600, 360);

        mFichier.setText("Fichier");

        jMenuItem1.setText("Exporter");
        mFichier.add(jMenuItem1);

        jMenuBar1.add(mFichier);

        mRepresentants.setText("Représentants");
        mRepresentants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mRepresentantsMouseClicked(evt);
            }
        });
        mRepresentants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRepresentantsActionPerformed(evt);
            }
        });
        jMenuBar1.add(mRepresentants);

        mClients.setText("Clients");
        mClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mClientsMouseClicked(evt);
            }
        });
        jMenuBar1.add(mClients);

        mProspects.setText("Prospects");
        mProspects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mProspectsMouseClicked(evt);
            }
        });
        jMenuBar1.add(mProspects);

        mAide.setText("Aide");
        jMenuBar1.add(mAide);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imageArbresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageArbresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imageArbresActionPerformed

    private void mRepresentantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRepresentantsActionPerformed
          
    }//GEN-LAST:event_mRepresentantsActionPerformed

    private void mRepresentantsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mRepresentantsMouseClicked
          AddRep dlg = null;
        try {
            dlg = new AddRep(new javax.swing.JFrame(), true);
        } catch (IOException ex) {
            Logger.getLogger(FenetrePrincipaleFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        dlg.setVisible(true);
    }//GEN-LAST:event_mRepresentantsMouseClicked

    private void mClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mClientsMouseClicked
        AddClient dlg = null;
        try {
            dlg = new AddClient(new javax.swing.JFrame(), true);
        } catch (IOException ex) {
            Logger.getLogger(FenetrePrincipaleFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        dlg.setVisible(true);
    }//GEN-LAST:event_mClientsMouseClicked

    private void mProspectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mProspectsMouseClicked
        AddProspect dlg = null;
        try {
            dlg = new AddProspect(new javax.swing.JFrame(), true);
        } catch (IOException ex) {
            Logger.getLogger(FenetrePrincipaleFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        dlg.setVisible(true);
    }//GEN-LAST:event_mProspectsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipaleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipaleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipaleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipaleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipaleFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton imageArbres;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBienvenue;
    private javax.swing.JLabel lbPresentation;
    private javax.swing.JLabel lbToutBoiscest;
    private javax.swing.JMenu mAide;
    private javax.swing.JMenu mClients;
    private javax.swing.JMenu mFichier;
    private javax.swing.JMenu mProspects;
    private javax.swing.JMenu mRepresentants;
    // End of variables declaration//GEN-END:variables

    public void setIcon(ImageIcon imageIcon) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
